id: P008151
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 13:04:47.871514
source_metadata:
  id: bdr:W23423
  title: གསུང་འབུམ། ཤེས་རབ་འོད་ཟེར།
  author: ''
  volumes:
    a3f244b22eec48ccb0a9a94ce8b566df:
      image_group_id: I1578
      title: ''
      volume_number: 1
      total_pages: 538
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
